# Generated by Django 5.1 on 2024-08-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedblockApp', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('proof', models.CharField(max_length=256)),
                ('data', models.TextField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
