# Generated by Django 5.1 on 2024-08-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedblockApp', '0003_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_id',
        ),
    ]
