# Generated by Django 5.1 on 2024-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedblockApp', '0004_remove_unit_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proof',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
