# Generated by Django 5.1.1 on 2024-10-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedblockApp', '0005_alter_block_proof_alter_block_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedblockApp.manufacturer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedblockApp.distributor'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedblockApp.retailer'),
        ),
    ]
