# Generated by Django 5.1.1 on 2024-10-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedblockApp', '0006_shipment_manufacturer_alter_shipment_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedblockApp.customer'),
        ),
    ]
